# Generated by Django 4.2.5 on 2023-09-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Feedback',
        ),
    ]
