# Generated by Django 4.2.5 on 2023-09-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('booking_date', models.DateField(verbose_name='Booking Date')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('no_of_people', models.CharField(max_length=200, verbose_name='No Of People')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Room')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomtype', verbose_name='Room Type')),
            ],
            options={
                'verbose_name_plural': 'Booking',
                'db_table': 'booking',
            },
        ),
    ]
