# Generated by Django 4.2.5 on 2023-09-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name_plural': 'Room Type',
                'db_table': 'room_types',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/img.png', upload_to='room', verbose_name='Image')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(max_length=2000, verbose_name='Text')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('price', models.IntegerField(default=10, verbose_name='Price')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomtype', verbose_name='Room Type')),
            ],
            options={
                'verbose_name_plural': 'Room',
                'db_table': 'room',
            },
        ),
    ]
