# Generated by Django 4.2.5 on 2023-09-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='default/img.png', upload_to='aboutUs', verbose_name='Title')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('about', models.TextField(max_length=2000, verbose_name='About')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name_plural': ' About Us',
                'db_table': 'about_us',
            },
        ),
    ]
