# Generated by Django 4.2.5 on 2023-09-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={},
        ),
    ]
